#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="salabeauty")]
public partial class dbcsdlDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttb_SanPham(tb_SanPham instance);
  partial void Updatetb_SanPham(tb_SanPham instance);
  partial void Deletetb_SanPham(tb_SanPham instance);
  partial void Insertkhachhang(khachhang instance);
  partial void Updatekhachhang(khachhang instance);
  partial void Deletekhachhang(khachhang instance);
  partial void Inserttb_LoaiSanPham(tb_LoaiSanPham instance);
  partial void Updatetb_LoaiSanPham(tb_LoaiSanPham instance);
  partial void Deletetb_LoaiSanPham(tb_LoaiSanPham instance);
  #endregion
	
	public dbcsdlDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["salabeautyConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tb_SanPham> tb_SanPhams
	{
		get
		{
			return this.GetTable<tb_SanPham>();
		}
	}
	
	public System.Data.Linq.Table<khachhang> khachhangs
	{
		get
		{
			return this.GetTable<khachhang>();
		}
	}
	
	public System.Data.Linq.Table<tb_LoaiSanPham> tb_LoaiSanPhams
	{
		get
		{
			return this.GetTable<tb_LoaiSanPham>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_SanPham")]
public partial class tb_SanPham : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sanpham_id;
	
	private string _sanpham_name;
	
	private System.Nullable<bool> _sanpham_new;
	
	private string _sanpham_image;
	
	private int _loaisanpham_id;
	
	private System.Nullable<int> _sanpham_luotmua;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsanpham_idChanging(int value);
    partial void Onsanpham_idChanged();
    partial void Onsanpham_nameChanging(string value);
    partial void Onsanpham_nameChanged();
    partial void Onsanpham_newChanging(System.Nullable<bool> value);
    partial void Onsanpham_newChanged();
    partial void Onsanpham_imageChanging(string value);
    partial void Onsanpham_imageChanged();
    partial void Onloaisanpham_idChanging(int value);
    partial void Onloaisanpham_idChanged();
    partial void Onsanpham_luotmuaChanging(System.Nullable<int> value);
    partial void Onsanpham_luotmuaChanged();
    #endregion
	
	public tb_SanPham()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int sanpham_id
	{
		get
		{
			return this._sanpham_id;
		}
		set
		{
			if ((this._sanpham_id != value))
			{
				this.Onsanpham_idChanging(value);
				this.SendPropertyChanging();
				this._sanpham_id = value;
				this.SendPropertyChanged("sanpham_id");
				this.Onsanpham_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_name", DbType="NChar(10)")]
	public string sanpham_name
	{
		get
		{
			return this._sanpham_name;
		}
		set
		{
			if ((this._sanpham_name != value))
			{
				this.Onsanpham_nameChanging(value);
				this.SendPropertyChanging();
				this._sanpham_name = value;
				this.SendPropertyChanged("sanpham_name");
				this.Onsanpham_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_new", DbType="Bit")]
	public System.Nullable<bool> sanpham_new
	{
		get
		{
			return this._sanpham_new;
		}
		set
		{
			if ((this._sanpham_new != value))
			{
				this.Onsanpham_newChanging(value);
				this.SendPropertyChanging();
				this._sanpham_new = value;
				this.SendPropertyChanged("sanpham_new");
				this.Onsanpham_newChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_image", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string sanpham_image
	{
		get
		{
			return this._sanpham_image;
		}
		set
		{
			if ((this._sanpham_image != value))
			{
				this.Onsanpham_imageChanging(value);
				this.SendPropertyChanging();
				this._sanpham_image = value;
				this.SendPropertyChanged("sanpham_image");
				this.Onsanpham_imageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_id", DbType="Int NOT NULL")]
	public int loaisanpham_id
	{
		get
		{
			return this._loaisanpham_id;
		}
		set
		{
			if ((this._loaisanpham_id != value))
			{
				this.Onloaisanpham_idChanging(value);
				this.SendPropertyChanging();
				this._loaisanpham_id = value;
				this.SendPropertyChanged("loaisanpham_id");
				this.Onloaisanpham_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham_luotmua", DbType="Int")]
	public System.Nullable<int> sanpham_luotmua
	{
		get
		{
			return this._sanpham_luotmua;
		}
		set
		{
			if ((this._sanpham_luotmua != value))
			{
				this.Onsanpham_luotmuaChanging(value);
				this.SendPropertyChanging();
				this._sanpham_luotmua = value;
				this.SendPropertyChanged("sanpham_luotmua");
				this.Onsanpham_luotmuaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _ten;
	
	private string _sdt;
	
	private string _email;
	
	private string _password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public khachhang()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string ten
	{
		get
		{
			return this._ten;
		}
		set
		{
			if ((this._ten != value))
			{
				this.OntenChanging(value);
				this.SendPropertyChanging();
				this._ten = value;
				this.SendPropertyChanged("ten");
				this.OntenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string sdt
	{
		get
		{
			return this._sdt;
		}
		set
		{
			if ((this._sdt != value))
			{
				this.OnsdtChanging(value);
				this.SendPropertyChanging();
				this._sdt = value;
				this.SendPropertyChanged("sdt");
				this.OnsdtChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_LoaiSanPham")]
public partial class tb_LoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _loaisanpham_id;
	
	private string _loaisanpham_name;
	
	private bool _loaisanpham_hidden;
	
	private string _loaisanpham_image;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onloaisanpham_idChanging(int value);
    partial void Onloaisanpham_idChanged();
    partial void Onloaisanpham_nameChanging(string value);
    partial void Onloaisanpham_nameChanged();
    partial void Onloaisanpham_hiddenChanging(bool value);
    partial void Onloaisanpham_hiddenChanged();
    partial void Onloaisanpham_imageChanging(string value);
    partial void Onloaisanpham_imageChanged();
    #endregion
	
	public tb_LoaiSanPham()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int loaisanpham_id
	{
		get
		{
			return this._loaisanpham_id;
		}
		set
		{
			if ((this._loaisanpham_id != value))
			{
				this.Onloaisanpham_idChanging(value);
				this.SendPropertyChanging();
				this._loaisanpham_id = value;
				this.SendPropertyChanged("loaisanpham_id");
				this.Onloaisanpham_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string loaisanpham_name
	{
		get
		{
			return this._loaisanpham_name;
		}
		set
		{
			if ((this._loaisanpham_name != value))
			{
				this.Onloaisanpham_nameChanging(value);
				this.SendPropertyChanging();
				this._loaisanpham_name = value;
				this.SendPropertyChanged("loaisanpham_name");
				this.Onloaisanpham_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_hidden", DbType="Bit NOT NULL")]
	public bool loaisanpham_hidden
	{
		get
		{
			return this._loaisanpham_hidden;
		}
		set
		{
			if ((this._loaisanpham_hidden != value))
			{
				this.Onloaisanpham_hiddenChanging(value);
				this.SendPropertyChanging();
				this._loaisanpham_hidden = value;
				this.SendPropertyChanged("loaisanpham_hidden");
				this.Onloaisanpham_hiddenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_image", DbType="NVarChar(MAX)")]
	public string loaisanpham_image
	{
		get
		{
			return this._loaisanpham_image;
		}
		set
		{
			if ((this._loaisanpham_image != value))
			{
				this.Onloaisanpham_imageChanging(value);
				this.SendPropertyChanging();
				this._loaisanpham_image = value;
				this.SendPropertyChanged("loaisanpham_image");
				this.Onloaisanpham_imageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
